version: '3'
services:
  nginx:
    image: nginx:stable
    container_name: gama_nginx
    restart: always
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/config/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/config/app.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - php
    networks:
      - app-network
  php:
      build:
        context: .
        dockerfile: ./docker/DockerFile
      restart: always
      container_name: gama_php
      volumes:
          - "./:/var/www"
          - ./docker/php_config/php.ini:/usr/local/etc/php/php.ini
      ports:
        - "9000:9000"
      networks:
        - app-network
  mysql:
      image: mysql:8.0
      container_name: gama_db
      restart: always
      ports:
        - "3306:3306"
      volumes:
        - my-datavolume:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_USER: ${DB_USERNAME}
        MYSQL_PASSWORD: ${DB_PASSWORD}
      networks:
        - app-network
  redis:
      image: redis:latest
      container_name: gama_redis
      restart: always
      ports:
          - "6379:6379"
      networks:
        - app-network
networks:
  app-network:
    driver: bridge
volumes:
  my-datavolume:
